// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewPost struct {
	Content  string `json:"content"`
	AuthorID string `json:"authorID"`
}

type Post struct {
	ID       string  `json:"id"`
	Content  *string `json:"content,omitempty"`
	AuthorID string  `json:"authorId"`
}

func (Post) IsEntity() {}

type Query struct {
}
