// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Post struct {
	ID       string `json:"id"`
	AuthorID string `json:"authorId"`
	Author   *User  `json:"author"`
}

func (Post) IsEntity() {}

type Query struct {
}

type User struct {
	ID   string  `json:"id"`
	Name *string `json:"name,omitempty"`
}

func (User) IsEntity() {}
